# Generated by Django 3.2.7 on 2021-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210926_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('max_speed', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=200, null=True)),
                ('carburant', models.CharField(blank=True, max_length=200, null=True)),
                ('consumption', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Ended', 'Ended')], max_length=200, null=True),
        ),
    ]
