# Generated by Django 3.2.7 on 2021-09-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210926_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carburant',
            field=models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Hybride', 'Hybride'), ('Essence', 'Essence'), ('Electrique', 'Electrique')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=200, null=True),
        ),
    ]
