# Generated by Django 3.2.7 on 2021-09-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='aubject',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lname',
        ),
    ]
